# Generated by Django 3.2.20 on 2023-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dietrestriction',
            fields=[
                ('restrictionid', models.AutoField(db_column='RestrictionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
            ],
            options={
                'db_table': 'dietrestriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientid', models.AutoField(db_column='IngredientID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100, unique=True)),
                ('category', models.CharField(db_column='Category', max_length=100)),
            ],
            options={
                'db_table': 'ingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeid', models.IntegerField(db_column='RecipeID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('mealtype', models.CharField(blank=True, db_column='MealType', max_length=100, null=True)),
                ('cuisine', models.CharField(blank=True, db_column='Cuisine', max_length=100, null=True)),
            ],
            options={
                'db_table': 'recipe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipedietrestriction',
            fields=[
                ('mappingid', models.AutoField(db_column='MappingID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipedietrestriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipeingredient',
            fields=[
                ('mappingid', models.AutoField(db_column='MappingID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'recipeingredient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdietrestriction',
            fields=[
                ('mappingid', models.AutoField(db_column='MappingID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userdietrestriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrecipe',
            fields=[
                ('mappingid', models.AutoField(db_column='MappingID', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='Datetime')),
            ],
            options={
                'db_table': 'userrecipe',
                'managed': False,
            },
        ),
    ]
