# Generated by Django 3.2.19 on 2023-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.AutoField(primary_key=True, serialize=False)),
                ('MealType', models.CharField(max_length=255)),
                ('Cuisine', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
    ]
